name: NotifierTrabalhaBoi
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    environment: PROD
    env:
      URL: ${{secrets.URL}}
      URL_AVAILABLE: ${{secrets.URL_AVAILABLE}}
      TOPIC: ${{secrets.TOPIC}}
      USERNAME: ${{secrets.USERNAME}}
      PASSWORD: ${{secrets.PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v3
      - name: Show env variables
        run: |
          env
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Python Script
        id: py-script
        run: |
          python mercadao.py
      - name: Commit and push changes
        run: |
          git config user.name "Pipeline Automation"
          git config user.email "github_actions@github.com"
          git add results.log
          git commit -m "Added results from build $GITHUB_RUN_NUMBER to logfile"
          git push
